#############################################################################
# Makefile for building: View
# Generated by qmake (2.01a) (Qt 4.8.6) on: Tue Nov 24 14:27:49 2015
# Project:  mipmap.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile mipmap.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DBABLIB_NAMESPACE_BEGIN= -DBABLIB_NAMESPACE_END= -DBABLIB_NAMESPACE_USE= -D"BABLIB_NAMESPACE_NAME(name)=name" -DBABLIB_GSL_SUPPORT -DGLEW_STATIC -DBABLIB_DEFAULT_PARAMS_FILE=default.par -DBABLIB_GLOBAL_DATA_PATH=/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/data -DBABLIB_GLOBAL_PARAMS_FILE=/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/config/bablib.par -DBABLIB_GLOBAL_QPROG_PATH=/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog -DQT_NO_DEBUG -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -fpermissive -std=c++11 -Wall -Wextra -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/bablib/src_bablib_gs_float/bablib -I/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/boost_pp/src -I/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16 -I/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/glew/src -I/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/constants -I/usr/X11R6/include -I/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/build/_home_latty___DEV_____LOISIRS___bablib_bablib_from_git_bablib_projects_projects_prog_texture_projects_mipmap/moc
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/X11R6/lib64 -L/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/bin -lbablib -lGLU -Wl,-rpath=/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer -L/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer -lQGLViewer -lglew -lgsl -lgslcblas -lQtXml -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = /home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/build/_home_latty___DEV_____LOISIRS___bablib_bablib_from_git_bablib_projects_projects_prog_texture_projects_mipmap/obj/

####### Files

SOURCES       = sources/main.cpp \
		sources/mipmap.cpp \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/constants/BablibConstants.cpp 
OBJECTS       = /home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/build/_home_latty___DEV_____LOISIRS___bablib_bablib_from_git_bablib_projects_projects_prog_texture_projects_mipmap/obj/main.o \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/build/_home_latty___DEV_____LOISIRS___bablib_bablib_from_git_bablib_projects_projects_prog_texture_projects_mipmap/obj/mipmap.o \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/build/_home_latty___DEV_____LOISIRS___bablib_bablib_from_git_bablib_projects_projects_prog_texture_projects_mipmap/obj/BablibConstants.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/config/paths.pri \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/config_project.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/bablib/config.pri \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/lib_config.pri \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/bablib.prf \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/boost_pp/config.pri \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/boost_pp.prf \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/libpng.prf \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/config.pri \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/qglviewer.prf \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/glew/config.pri \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/glew.prf \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/constants/config.pri \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/constants.prf \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/gsl.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		mipmap.pro
QMAKE_TARGET  = View
DESTDIR       = 
TARGET        = View

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  /home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/bin/libbablib.a /home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/bin/libglew.a
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mipmap.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/config/paths.pri \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/config_project.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/bablib/config.pri \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/lib_config.pri \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/bablib.prf \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/boost_pp/config.pri \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/boost_pp.prf \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/libpng.prf \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/config.pri \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/qglviewer.prf \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/glew/config.pri \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/glew.prf \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/constants/config.pri \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/constants.prf \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/gsl.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/libQGLViewer.prl \
		/usr/lib/x86_64-linux-gnu/libQtXml.prl \
		/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile mipmap.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/config/paths.pri:
/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/config_project.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/bablib/config.pri:
/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/lib_config.pri:
/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/bablib.prf:
/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/boost_pp/config.pri:
/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/boost_pp.prf:
/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/libpng.prf:
/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/config.pri:
/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/qglviewer.prf:
/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/glew/config.pri:
/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/glew.prf:
/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/constants/config.pri:
/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/constants.prf:
/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/qtfeatures/gsl.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/libQGLViewer.prl:
/usr/lib/x86_64-linux-gnu/libQtXml.prl:
/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile mipmap.pro

dist: 
	@$(CHK_DIR_EXISTS) /home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/build/_home_latty___DEV_____LOISIRS___bablib_bablib_from_git_bablib_projects_projects_prog_texture_projects_mipmap/obj/View1.0.0 || $(MKDIR) /home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/build/_home_latty___DEV_____LOISIRS___bablib_bablib_from_git_bablib_projects_projects_prog_texture_projects_mipmap/obj/View1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) /home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/build/_home_latty___DEV_____LOISIRS___bablib_bablib_from_git_bablib_projects_projects_prog_texture_projects_mipmap/obj/View1.0.0/ && $(COPY_FILE) --parents sources/helper_debug.h sources/helper_destroy.h sources/helper_draw.h sources/helper_init.h sources/helper_preprocess.h sources/helper_update.h sources/helpers.h sources/mipmap.h /home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/constants/BablibConstants.h /home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/build/_home_latty___DEV_____LOISIRS___bablib_bablib_from_git_bablib_projects_projects_prog_texture_projects_mipmap/obj/View1.0.0/ && $(COPY_FILE) --parents sources/main.cpp sources/mipmap.cpp /home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/constants/BablibConstants.cpp /home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/build/_home_latty___DEV_____LOISIRS___bablib_bablib_from_git_bablib_projects_projects_prog_texture_projects_mipmap/obj/View1.0.0/ && (cd `dirname /home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/build/_home_latty___DEV_____LOISIRS___bablib_bablib_from_git_bablib_projects_projects_prog_texture_projects_mipmap/obj/View1.0.0` && $(TAR) View1.0.0.tar View1.0.0 && $(COMPRESS) View1.0.0.tar) && $(MOVE) `dirname /home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/build/_home_latty___DEV_____LOISIRS___bablib_bablib_from_git_bablib_projects_projects_prog_texture_projects_mipmap/obj/View1.0.0`/View1.0.0.tar.gz . && $(DEL_FILE) -r /home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/build/_home_latty___DEV_____LOISIRS___bablib_bablib_from_git_bablib_projects_projects_prog_texture_projects_mipmap/obj/View1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: /home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/build/_home_latty___DEV_____LOISIRS___bablib_bablib_from_git_bablib_projects_projects_prog_texture_projects_mipmap/ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) /home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/build/_home_latty___DEV_____LOISIRS___bablib_bablib_from_git_bablib_projects_projects_prog_texture_projects_mipmap/ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/build/_home_latty___DEV_____LOISIRS___bablib_bablib_from_git_bablib_projects_projects_prog_texture_projects_mipmap/obj/main.o: sources/main.cpp sources/mipmap.h \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/qglviewer.h \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/camera.h \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/manipulatedCameraFrame.h \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/manipulatedFrame.h \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/frame.h \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/constraint.h \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/vec.h \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/config.h \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/quaternion.h \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/mouseGrabber.h \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/keyFrameInterpolator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/build/_home_latty___DEV_____LOISIRS___bablib_bablib_from_git_bablib_projects_projects_prog_texture_projects_mipmap/obj/main.o sources/main.cpp

/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/build/_home_latty___DEV_____LOISIRS___bablib_bablib_from_git_bablib_projects_projects_prog_texture_projects_mipmap/obj/mipmap.o: sources/mipmap.cpp sources/mipmap.h \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/qglviewer.h \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/camera.h \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/manipulatedCameraFrame.h \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/manipulatedFrame.h \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/frame.h \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/constraint.h \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/vec.h \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/config.h \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/quaternion.h \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/mouseGrabber.h \
		/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/qglviewer/libQGLViewer-2.3.16/QGLViewer/keyFrameInterpolator.h \
		sources/helpers.h \
		sources/helper_preprocess.h \
		sources/helper_init.h \
		sources/helper_destroy.h \
		sources/helper_update.h \
		sources/helper_draw.h \
		sources/helper_debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/build/_home_latty___DEV_____LOISIRS___bablib_bablib_from_git_bablib_projects_projects_prog_texture_projects_mipmap/obj/mipmap.o sources/mipmap.cpp

/home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/build/_home_latty___DEV_____LOISIRS___bablib_bablib_from_git_bablib_projects_projects_prog_texture_projects_mipmap/obj/BablibConstants.o: /home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/constants/BablibConstants.cpp /home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/constants/BablibConstants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/build/_home_latty___DEV_____LOISIRS___bablib_bablib_from_git_bablib_projects_projects_prog_texture_projects_mipmap/obj/BablibConstants.o /home/latty/__DEV__/__LOISIRS__/bablib/bablib_from_git/qprog/libs/constants/BablibConstants.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

